### ISSUE TITLE
Shader not working on Android

### ISSUE THREAD

**Issue by schaubli** [jose-villegas/LowPolyWater#1]
I downloaded the project in Unity (5.3.1x32) I switched to Android Platform and the water disappeared.
It was fine on the Web Player Platform.
![lowpshader](https://cloud.githubusercontent.com/assets/18361732/19170624/86cba872-8c19-11e6-9082-8001dd508634.JPG)
![lowpeditor](https://cloud.githubusercontent.com/assets/18361732/19170625/86cfca38-8c19-11e6-9878-233e248be035.JPG)

You can see that the outlines of the mesh are still shown in the scene but the vertices are not shaded

**Comment by jose-villegas** [comment]
That's probably because the shader has a geometry shader stage.
http://answers.unity3d.com/questions/1160468/unity-5-geometry-shader-broken-on-android.html

You may want to look into achieving the flat shading effect eliminating shared vertices.
http://answers.unity3d.com/questions/798510/flat-shading.html

**Comment by schaubli** [comment]
Hi and thank you for your quick answer. :)

I switched the Graphics Emulation and exchanged the mesh with the generated
mesh without shared verticies. I'm also using a Samsung S7 with the latest
Android version. But I still don't see the water due to the still present
geometry shader. Is there a was to rewrite the LowPolyWater Standard shader
so that it no longer needs the geometry part? I tried this but due to my
small knowledge of Shaders i couldn't get it to work :(

I am trying to implement your shader into a project at my University which
is an Augmented- and Virtual-Reality Game in the LowPoly look. So i could
really use your Asset :)

Best regards,

Linus Schaub

2016-10-07 0:00 GMT+02:00 José Villegas notifications@github.com:

**Comment by jose-villegas** [comment]
Well the flat shading with non-shared vertices and the water simulation doesn't seem to look like I want.

Nonetheless I uploaded a version of the shader without the geometry stage (all the lighting happens on the vertex shader instead). I can't do much here with the incompatibilities on Android, check this out may be related https://issuetracker.unity3d.com/issues/android-es3-dot-1-geometry-shaders-do-not-render-on-mali-devices
